name: Java Selenium Maven TestNG CI

on:
  pull_request:
    branches: [main]

env:
  JAVA_VERSION: 17

jobs:
  run-test:
    name: 'Run tests'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install JDK
        uses: actions/setup-java@v2
        with:
             java-version: '17'
             distribution: 'adopt'

      - name: Cache maven
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('./pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Archive Test Results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: target/surefire-reports/

      - name: Upload TestNG Reports
        uses: mikepenz/action-test-reporter@v2
        with:
          files: target/surefire-reports/TEST-*.xml

      - name: Maven test
        run: mvn test
        env:
          CHROME_OPTIONS: --disable-gpu;--no-sandbox;--disable-dev-shm-usage;--headless=new;--window-size=1920,1080
          CI_RUN: true

      - merge:
        runs-on: ubuntu-latest

        needs: [ build ]

        steps:
          - name: Checkout repository
            uses: actions/checkout@v2

          - name: Merge pull request
            uses: actions/github-script@v4
            with:
              github-token: ${{ secrets.GITHUB_TOKEN }}
              script: |
                const prNumber = context.payload.pull_request.number;
                const octokit = github.getOctokit(process.env.GITHUB_TOKEN);
                await octokit.pulls.merge({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  pull_number: prNumber,
                });
